export enum Storage {
    API = 'api-storage',
    EngineData = 'enginedata-storage',
    KV = 'kvdata-storage',
    TextFilter = 'textfilter-storage',
    AppMode = 'appmode-storage',
    BackgroundImage = 'background-image-storage',
    UserCard = 'usercard-storage',
    Instruct = 'instruct-storage',
    Logs = 'logstate-storage',
    Samplers = 'samplerstate-storage',
    TTS = 'tts-data-storage',
    ColorState = 'colorscheme-storage',
    TagHider = 'tag-hider-storage',
    CharacterSearch = 'storage-character-search',
}
