name: Build Gemu Edition APK

on: 
  workflow_dispatch: 

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Packages
        run: npm install --legacy-peer-deps

      - name: Build Android App Engine
        run: npx expo prebuild --platform android

      - name: Compile APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload Finished APK
        uses: actions/upload-artifact@v3
        with:
          name: ChatterUI-Gemu-Edition
          path: android/app/build/outputs/apk/release/app-release.apk
